//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERP_desktop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Amount { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
    }
}
