//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERP_desktop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.DetailRow = new HashSet<DetailRow>();
            this.InvoiceItem = new HashSet<InvoiceItem>();
            this.TotalRow = new HashSet<TotalRow>();
        }
    
        public int ID { get; set; }
        public string BackColor { get; set; }
        public string TextColor { get; set; }
        public string ImagePath { get; set; }
        public string Title { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Footer { get; set; }
        public Nullable<bool> CompanyOrientation { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailRow> DetailRow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalRow> TotalRow { get; set; }
    }
}
